# Site settings

# REQUIRED CHANGES
title: Konstantinos Smanis | Professional Portfolio
url: "https://ksmanis.github.io"
baseurl: ""

# OPTIONAL CHANGES
project-page-label: Projects
essay-page-label: Reports

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]
